modified=false

[functional]
left_ip="1.0.0.0"
right_ip="2.0.0.0" 
left_brightness="0"
right_brightness="0"
energy_mode="0"
left_flip_x=false
right_flip_x=false
flip_y=false
left_rotate_angle=0 
right_rotate_angle=0     

[functional.left_rect]
x=0
y=0
width=1
height=1

[functional.right_rect]
x=0
y=0
width=1
height=1

[params]
left_calib_xmin=0
left_calib_xmax=0
left_calib_ymin=0
left_calib_ymax=0
left_calib_xoff=0
left_calib_yoff=0
left_has_calibration=false
right_calib_xmin=0
right_calib_xmax=0
right_calib_ymin=0
right_calib_ymax=0
right_calib_xoff=0
right_calib_yoff=0
right_has_calibration=false
left_eye_fully_open=0
left_eye_fully_closed=0
right_eye_fully_open=0
right_eye_fully_closed=0