modified = false

[functional]
brightness=0
rotate_angle=0
energy_mode=0
use_filter=false
wifi_ip="0.0.0.0"

[functional.rect]
x=0
y=0
width=1
height=1


[params]
cheek_puff_left_offset=0
cheek_puff_right_offset=0
jaw_open_offset=0
tongue_out_offset=0
mouth_close_offset=0
mouth_funnel_offset=0
mouth_pucker_offset=0
mouth_roll_upper_offset=0
mouth_roll_lower_offset=0
mouth_shrug_upper_offset=0
mouth_shrug_lower_offset=0
cheek_puff_left_gain=0
cheek_puff_right_gain=0
jaw_open_gain=0
tongue_out_gain=0
mouth_close_gain=0
mouth_funnel_gain=0
mouth_pucker_gain=0
mouth_roll_upper_gain=0
mouth_roll_lower_gain=0
mouth_shrug_upper_gain=0
mouth_shrug_lower_gain=0

[filter]
kalman_dt=0
kalman_q_factor=0
r_factor=0